package com.cdd_game;

public enum State {
    INIT,
    SERVER_SETTING,
    SERVER_WAITING,
    SERVER_PLAYING,
    CLIENT_WAITING,
    CLIENT_READY,
    CLIENT_SCANNING_GAME_ROOM,
    CLIENT_PLAYING,
    SETTLEMENT
}

